import '@/models/Announcement'
import '@/models/Asset'
import '@/models/AssetRequest'
import '@/models/Attendance'
import '@/models/Branch'
import '@/models/Candidate'
import '@/models/Department'
import '@/models/Designation'
import '@/models/Employee'
import '@/models/EmployeeDocument'
import '@/models/Expense'
import '@/models/HelpdeskTicket'
import '@/models/Holiday'
import '@/models/Kra'
import '@/models/LeaveBalance'
import '@/models/LeaveRequest'
import '@/models/LeaveType'
import '@/models/Payslip'
import '@/models/Permission'
import '@/models/PerformanceReview'
import '@/models/Resignation'
import '@/models/Roster'
import '@/models/SalaryStructure'
import '@/models/Shift'
import '@/models/Task'
import '@/models/TeamRequest'
import '@/models/TrainingSession'

export function ensureTenantModelSchemasLoaded() {
  return true
}
