const MODEL_LOADERS = [
  () => import('@/models/Announcement'),
  () => import('@/models/Application'),
  () => import('@/models/ApplicationAnswer'),
  () => import('@/models/ApplicationStageHistory'),
  () => import('@/models/Asset'),
  () => import('@/models/AssessmentEvaluation'),
  () => import('@/models/AssessmentOption'),
  () => import('@/models/AssessmentQuestion'),
  () => import('@/models/AssessmentTemplate'),
  () => import('@/models/AssetRequest'),
  () => import('@/models/Attendance'),
  () => import('@/models/Branch'),
  () => import('@/models/Candidate'),
  () => import('@/models/CandidateAssessment'),
  () => import('@/models/CandidateAssessmentAnswer'),
  () => import('@/models/CandidateCertification'),
  () => import('@/models/CandidateEducation'),
  () => import('@/models/CandidateExperience'),
  () => import('@/models/CandidateProject'),
  () => import('@/models/CandidateJobMatch'),
  () => import('@/models/CandidateResume'),
  () => import('@/models/CandidateSkill'),
  () => import('@/models/CandidateTag'),
  () => import('@/models/CandidateDocument'),
  () => import('@/models/CandidateDocumentVersion'),
  () => import('@/models/CandidateTagAssignment'),
  () => import('@/models/CompensationApproval'),
  () => import('@/models/CompensationProposal'),
  () => import('@/models/Department'),
  () => import('@/models/Designation'),
  () => import('@/models/DocumentRequirement'),
  () => import('@/models/Employee'),
  () => import('@/models/EmployeeCodeSequence'),
  () => import('@/models/EmployeeDocument'),
  () => import('@/models/Expense'),
  () => import('@/models/HelpdeskTicket'),
  () => import('@/models/Holiday'),
  () => import('@/models/Interview'),
  () => import('@/models/InterviewFeedback'),
  () => import('@/models/InterviewFeedbackScore'),
  () => import('@/models/InterviewPanelMember'),
  () => import('@/models/InterviewScheduleHistory'),
  () => import('@/models/InterviewScorecardCriterion'),
  () => import('@/models/InterviewScorecardTemplate'),
  () => import('@/models/Job'),
  () => import('@/models/JobApplicationField'),
  () => import('@/models/JobPipelineStage'),
  () => import('@/models/JobPublication'),
  () => import('@/models/JobRequisition'),
  () => import('@/models/JobScreeningQuestion'),
  () => import('@/models/JobSkill'),
  () => import('@/models/Kra'),
  () => import('@/models/LeaveBalance'),
  () => import('@/models/LeaveRequest'),
  () => import('@/models/LeaveType'),
  () => import('@/models/Offer'),
  () => import('@/models/OfferAccessToken'),
  () => import('@/models/OfferApproval'),
  () => import('@/models/OfferCandidateAction'),
  () => import('@/models/OfferTemplate'),
  () => import('@/models/OfferVersion'),
  () => import('@/models/Payslip'),
  () => import('@/models/Permission'),
  () => import('@/models/PerformanceReview'),
  () => import('@/models/Preboarding'),
  () => import('@/models/PreboardingAccessToken'),
  () => import('@/models/PreboardingBankDetails'),
  () => import('@/models/PreboardingEducation'),
  () => import('@/models/PreboardingEmergencyContact'),
  () => import('@/models/PreboardingEmploymentHistory'),
  () => import('@/models/PreboardingPersonalDetails'),
  () => import('@/models/PreboardingStatutoryDetails'),
  () => import('@/models/RecruitmentIntegration'),
  () => import('@/models/RecruitmentSettings'),
  () => import('@/models/RequisitionSkill'),
  () => import('@/models/Resignation'),
  () => import('@/models/Roster'),
  () => import('@/models/SalaryStructure'),
  () => import('@/models/SelectionDecision'),
  () => import('@/models/Shift'),
  () => import('@/models/TeamRequest'),
  () => import('@/models/TrainingSession'),
]

let loaded = false
let loadingPromise = null

export async function ensureTenantModelSchemasLoaded() {
  if (loaded) return
  if (!loadingPromise) {
    loadingPromise = Promise.all(MODEL_LOADERS.map((load) => load())).then(() => {
      loaded = true
    })
  }
  await loadingPromise
}
